apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pvc-slave1-1
  namespace: fio
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
